Repository andela/mervels-bn-frontend, pull requests merged in 2019-11, with the labels that each got.

#4 #168131514 setting up an empty react project
  .eslintignore
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .huskyrc.json
  .lintstagedrc.json
  README.md
  config/env.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/webpack.config.js
  config/webpackDevServer.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  scripts/build.js
  scripts/start.js
  scripts/test.js
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
Labels: waiting TTL approval

#3 Ch setup redux 168131515
  .eslintignore
  package-lock.json
  src/App.js
  src/redux/actions/actionType.js
  src/redux/reducers/index.js
  src/redux/store.js
Labels: Ready for review

#6 #169502584 error logger
  app.json
  config/index.js
  package-lock.json
  package.json
  src/__tests__/App.js
  src/index.js
Labels: waiting TTL approval

#8 #168131517 Update TravisCI to run tests
  .gitignore
  .travis.yml
  package-lock.json
Labels: Ready for review

#10 #168131520 Run codeclimate test coverage
  .circleci/config.yml
  README.md
  src/serviceWorker.js
Labels: waiting TTL approval

#7 #168131516 Set up tests on the client
  src/App.test.js
  src/config/index.js
  src/index.js
Labels: waiting TTL approval

#5 #168131519 Setup SASS processing on the client
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/index.js
  src/index.scss
Labels: waiting TTL approval

#13 #168131521 Create the client README file
  README.md
Labels: Ready for review

#9 chore(react-router): setup react-router
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/PrivateRoute.js
  src/components/DashboardPage.js
  src/components/HomePage.js
  src/components/LoggedInDashboard.js
  src/components/LoginPage.js
  src/index.js
  src/sentry_config.js
Labels: waiting TTL approval

#12 #168131522 Configure storybook for component development
  .gitignore
  .storybook/addons.js
  .storybook/barefootTheme.js
  .storybook/config.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/serviceWorker.js
  src/stories/images/marvel_logo.png
  src/stories/index.stories.js
Labels: waiting TTL approval

#18 #168131523 Users should be able Signup/Register to Barefoot Nomad
  .eslintrc
  config/webpack.config.js
  package-lock.json
  package.json
  public/index.html
  src/API/userApi.js
  src/App.js
  src/App.scss
  src/__tests__/components/CallForVerify.test.js
  src/__tests__/components/ReverifyPage.test.js
  src/__tests__/components/SignupPage.test.js
  src/__tests__/components/VerifyEmailPage.test.js
  src/__tests__/components/shared/Input.test.js
  src/__tests__/components/shared/Spinner.test.js
  src/__tests__/redux/actions/reverifyAction.test.js
  src/__tests__/redux/actions/signupAction.test.js
  src/__tests__/redux/actions/verifyAction.test.js
  src/__tests__/redux/reducers/reverifyReducer.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/__tests__/redux/reducers/verifyReducer.test.js
  src/components/CallForVerify.js
  src/components/ReverifyPage.js
  src/components/VerifyEmailPage.js
  src/components/shared/Input.js
  src/components/shared/Spinner.js
  src/components/signupPage.js
  src/config/enzyme.config.js
  src/helpers/validator.js
  src/redux/actions/actionType.js
  src/redux/actions/actionTypes.js
  src/redux/actions/reverifyActions.js
  src/redux/actions/signupActions.js
  src/redux/actions/verifyAction.js
  src/redux/reducers/index.js
  src/redux/reducers/reverifyReducer.js
  src/redux/reducers/signupReducer.js
  src/redux/reducers/verifyReducer.js
  src/stories/index.stories.js
  src/stories/signUp/Input.stories.js
  src/stories/signUp/signupPage.stories.js
  src/stories/signUp/verify.stories.js
  src/styles/call4verify.scss
  src/styles/index.scss
  src/styles/reverify.scss
  src/styles/signup.scss
  src/styles/styles.scss
  src/styles/verify.scss
Labels: Ready for review

#17 #168131525 Users should be able to Login to Barefoot Nomad
  .gitignore
  browserMocks.js
  enzyme.config.js
  package.json
  public/index.html
  src/App.js
  src/PrivateRoute.js
  src/__tests__/components/LoginPage.js
  src/__tests__/components/__snapshots__/LoginPage.js.snap
  src/__tests__/components/shared/__snapshots__/socialAuth.js.snap
  src/__tests__/components/shared/socialAuth.js
  src/__tests__/redux/actions/login.js
  src/__tests__/redux/reducers/login.js
  src/components/LoginPage.js
  src/components/VerifyEmailPage.js
  src/components/shared/socialAuth.js
  src/config/index.js
  src/index.js
  src/index.scss
  src/logo/iconfinder_Google_1298745.png
  src/logo/iconfinder_square-facebook_317727.png
  src/logo/logo@2x.png
  src/redux/actions/actionTypes.js
  src/redux/actions/login.js
  src/redux/reducers/index.js
  src/redux/reducers/login.js
  src/stories/index.stories.js
  src/stories/login/login.stories.js
  src/styles/App.scss
  src/styles/index.scss
  src/styles/login.scss
Labels: Ready for review

#15 #168131528 Implement requests table
  package.json
  src/App.js
  src/__tests__/components/RequestView.test.js
  src/__tests__/redux/actions/requestsAction.test.js
  src/__tests__/redux/reducers/requestsReducer.test.js
  src/components/HomePage.js
  src/components/iconStyles.js
  src/components/requestsPage.js
  src/components/shared/tableComponent.js
  src/redux/actions/actionType.js
  src/redux/actions/requestsAction.js
  src/redux/reducers/index.js
  src/redux/reducers/requestsReducers.js
  src/styles/App.scss
  src/styles/table.scss
Labels: Ready for review

#16 #168131524 Users should be presented with a reset password link
  .DS_Store
  .vscode/settings.json
  config/webpack.config.js
  package-lock.json
  src/.DS_Store
  src/App.js
  src/__tests__/components/LoginPage.js
  src/__tests__/components/ResetPassword/ResetPasswordForm.snapshot.test.js
  src/__tests__/components/ResetPassword/ResetPasswordPage.test.js
  src/__tests__/components/ResetPassword/__snapshots__/ResetPasswordForm.snapshot.test.js.snap
  src/__tests__/components/shared/Input.test.js
  src/__tests__/components/shared/input.js
  src/__tests__/redux/actions/errorAction.js
  src/__tests__/redux/actions/resetPass.js
  src/__tests__/redux/actions/resetPassword.js
  src/__tests__/redux/reducers/errorReducer.js
  src/__tests__/redux/reducers/resetPasswordReducer.js
  src/components/LoginPage.js
  src/components/PageNotFound.js
  src/components/Profile.js
  src/components/ResetPassword/ResetPasswordForm.js
  src/components/ResetPassword/ResetPasswordPage.js
  src/components/ReverifyPage.js
  src/components/shared/input.js
  src/components/signupPage.js
  src/helpers/validator.js
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/errorActions.js
  src/redux/actions/resetPassword.js
  src/redux/actions/reverifyActions.js
  src/redux/actions/signupActions.js
  src/redux/actions/verifyAction.js
  src/redux/reducers/errorReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/resetPasswordReducer.js
  src/styles/login.scss
  src/styles/resetPassword.scss
Labels: Ready for review

#19 Ft notification panel 168131529
  config/webpack.config.js
  package-lock.json
  package.json
  src/API/notificationApi.js
  src/API/userApi.js
  src/App.js
  src/__mock_data__/notifications.js
  src/__tests__/components/NotificationPane.test.js
  src/__tests__/components/Notifications.test.js
  src/__tests__/components/shared/Navbar.test.js
  src/__tests__/redux/actions/notificationAction.test.js
  src/__tests__/redux/reducers/notificationReducer.test.js
  src/__tests__/redux/reducers/resetPasswordReducer.js
  src/assets/pic.png
  src/components/HomePage.js
  src/components/LoggedInDashboard.js
  src/components/LoginPage.js
  src/components/NotificationPane.js
  src/components/Notifications.js
  src/components/ProfilePage.js
  src/components/common/input.js
  src/components/requestsPage.js
  src/components/shared/iconStyles.js
  src/components/shared/navbarComponent.js
  src/components/singleRequestPage.js
  src/config/axiosInstance.js
  src/config/sockets.js
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/login.js
  src/redux/actions/notificationActions.js
  src/redux/actions/profileAction.js
  src/redux/actions/requestsAction.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/notificationReducer.js
  src/redux/reducers/profileReducer.js
  src/stories/signUp/Input.stories.js
  src/styles/App.scss
  src/styles/notification.scss
  src/styles/signup.scss
Labels: Ready for review

#22 #168131530 add request header panel
  src/App.js
  src/__tests__/components/LoginPage.js
  src/__tests__/components/RequestView.test.js
  src/__tests__/components/__snapshots__/headerPanel.test.js.snap
  src/__tests__/components/approvalPage.test.js
  src/__tests__/components/headerPanel.test.js
  src/__tests__/helpers/search.test.js
  src/__tests__/redux/actions/approvalsActions.test.js
  src/__tests__/redux/actions/requestsAction.test.js
  src/__tests__/redux/reducers/requestApprovalsReducer.test.js
  src/__tests__/redux/reducers/requestsReducer.test.js
  src/components/AccessForbiddenPage.js
  src/components/approvalsPage.js
  src/components/headerPanel.js
  src/components/requestsPage.js
  src/components/shared/Pagination.js
  src/components/shared/SidebarComponent.js
  src/components/shared/TooltipComponent.js
  src/components/shared/defaultButton.js
  src/components/shared/navbarComponent.js
  src/components/shared/tableComponent.js
  src/helpers/search.js
  src/logo/logo-long.png
  src/logo/thailand.jpg
  src/redux/actions/actionType.js
  src/redux/actions/actionTypes.js
  src/redux/actions/approvalsActions.js
  src/redux/actions/requestsAction.js
  src/redux/reducers/index.js
  src/redux/reducers/requestApprovalsReducer.js
  src/redux/reducers/requestsReducers.js
  src/styles/403.scss
  src/styles/App.scss
  src/styles/_small-default.scss
  src/styles/index.scss
  src/styles/login.scss
  src/styles/pagination.scss
  src/styles/sidebar.scss
  src/styles/table.scss
  src/styles/tooltip.scss
Labels: Ready for review

#21 #168131531 Approvals Table
  .circleci/config.yml
  package-lock.json
  src/App.js
  src/App.scss
  src/__tests__/components/RequestView.test.js
  src/__tests__/components/approvalPage.test.js
  src/components/approvalsPage.js
  src/components/requestsPage.js
  src/components/shared/Pagination.js
  src/components/shared/SidebarComponent.js
  src/components/shared/tableComponent.js
  src/redux/actions/approvalsActions.js
  src/styles/App.scss
Labels: Ready for review

#20 #168131534 Avail Requests for Approval
  src/.DS_Store
  src/API/managerApi.js
  src/API/userApi.js
  src/App.js
  src/__tests__/components/ApproveReject.test.js
  src/__tests__/components/Notifications.test.js
  src/__tests__/components/VerifyEmailPage.test.js
  src/__tests__/components/shared/TravelDetails.test.js
  src/__tests__/redux/actions/approveReject.test.js
  src/__tests__/redux/actions/requestAction.test.js
  src/__tests__/redux/actions/reverifyAction.test.js
  src/__tests__/redux/actions/signupAction.test.js
  src/__tests__/redux/actions/verifyAction.test.js
  src/__tests__/redux/reducers/approveRejectReducer.test.js
  src/__tests__/redux/reducers/getRequestReducer.test.js
  src/components/ApproveReject.js
  src/components/ReverifyPage.js
  src/components/approvalsPage.js
  src/components/requestsPage.js
  src/components/shared/TravelDetails.js
  src/components/shared/TravelReason.js
  src/components/shared/tableComponent.js
  src/components/signupPage.js
  src/helpers/validator.js
  src/redux/actions/actionTypes.js
  src/redux/actions/approveRejectAction.js
  src/redux/actions/notificationActions.js
  src/redux/actions/profileAction.js
  src/redux/actions/requestAction.js
  src/redux/actions/requestsAction.js
  src/redux/actions/resetPassword.js
  src/redux/actions/reverifyActions.js
  src/redux/actions/signupActions.js
  src/redux/actions/verifyAction.js
  src/redux/reducers/SingleRequestReducer.js
  src/redux/reducers/approveRejectReducer.js
  src/redux/reducers/index.js
  src/stories/request/singleRequest.stories.js
  src/styles/App.scss
  src/styles/signup.scss
  src/styles/singleRequestManager.scss
  src/styles/traveReason.scss
Labels: Ready for review

#28 #168131547 As a manager I should get a re-confirmation dialog for approving or rejecting travel requests
  .vscode/settings.json
  src/__tests__/components/ApproveReject.test.js
  src/components/ApproveReject.js
  src/redux/actions/approveRejectAction.js
  src/redux/actions/requestAction.js
  src/redux/actions/reverifyActions.js
  src/redux/actions/signupActions.js
  src/styles/singleRequestManager.scss
Labels: ready for merge

#29 #168131532 User Role Settings UI
  src/API/userApi.js
  src/App.js
  src/__tests__/components/shared/Navbar.test.js
  src/__tests__/components/userRolePage.test.js
  src/__tests__/redux/actions/superAdminAction.test.js
  src/__tests__/redux/reducers/superAdminReducer.test.js
  src/components/UserRolesPage.js
  src/components/approvalsPage.js
  src/components/shared/Sidebar.js
  src/components/shared/SidebarComponent.js
  src/components/shared/input.js
  src/helpers/updateableRequest.js
  src/helpers/validator.js
  src/redux/actions/actionTypes.js
  src/redux/actions/superAdminAction.js
  src/redux/reducers/index.js
  src/redux/reducers/superAdminReducers.js
  src/styles/App.scss
  src/styles/role.scss
Labels: Ready for review

#31 #168131536 Profile Information from Travel Request Page(UI)
  .DS_Store
  src/__tests__/components/CreateOrEditRequest.js
  src/__tests__/components/multiCityRequest.js
  src/__tests__/components/oneWayRequest.js
  src/__tests__/components/returnTripRequest.js
  src/__tests__/components/viewRequest.js
  src/__tests__/redux/actions/profile.js
  src/__tests__/redux/actions/request.js
  src/components/CreateOrEditRequest.js
  src/components/MultiCityRequest.js
  src/components/OneWayRequest.js
  src/components/ProfilePage.js
  src/components/ReturnRequest.js
  src/redux/actions/requestActions.js
  src/redux/reducers/profileReducer.js
  src/styles/App.scss
Labels: Ready for review
